server:
  port: 8085

  tomcat:
    accept-count: 6000
    threads:
      max: 800
      min-spare: 100
    accesslog:
      enabled: true
      directory: "./tomcat"
      pattern: "%h %1 %u '%r' %s %b %D"

spring:
  application:
    name: seckill-stock

  profiles:
    include: data



rocketmq:
  name-server: 192.168.1.61:9876
  producer:
    group: order-group

dubbo:
  registry:
    address: nacos://192.168.1.61:8848
    protocol: nacos
  protocol:
    name: dubbo
    port: 20885
  application:
    name: ${spring.application.name}
    qos-enable: false


seata:
  application-id: ${spring.application.name}-seata
  tx-service-group: seata-order-tcc-group
  service:
    vgroup-mapping:
      seata-order-tcc-group: default
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.1.61:8848
      namespace: Seckill-Distributed-Transaction
      cluster: default
      group: SEATA-GROUP
  config:
    type: nacos
    nacos:
      server-addr: 192.168.1.61:8848
      namespace: Seckill-Distributed-Transaction
      group: SEATA-GROUP